### ISSUE TITLE
Mod not working with neither latest or experimental builds.

### ISSUE THREAD

**Issue by OathUnbroken** [wund3rcr4zy/by-the-book#1]
1. When I open my saved game, I automatically start out with the private eye sync disk installed without ever having to buy it and install it.
2. When I pick up any other sync disk that is not the private eye disk, they are all transformed into the private eye sync disk in the sync disk screen and when they are installed, they are installed as the private eye disk.
3. When I arrive at any crime scene, the perk that comes with the disk just straight up doesn't work and I am still committing the trespassing crime and am usually shot dead by police. (both before and after the crime tape is placed by them)

Please fix this as I we all really need this mod!

side note: I've also tried placing this mod at both the top and bottom of the load order and neither worked.
(via Thunderstore R2 mod manager)

**Comment by wund3rcr4zy** [comment]
Hello, and thanks for filing a bug report.  Bug reports like these will help me find what's wrong.
I did expect there to be issues with this mod as it's my first attempt (hence it not being 1.0.0 and instead 0.0.2).

The mod works by adding a "Guest Pass" to the crime location, so you'll know it's working as intended if you immediately get a guest pass when a new murder occurs and you have the sync disk installed.

I'll try today to track down why this is happening for you, I did not have the same thing happen for me using the experimental branch of the game and when downloading the released mod from thunderstore.
