### ISSUE TITLE
Sync Disk Possibly Overwriting other upgrade features/

### ISSUE THREAD

**Issue by wund3rcr4zy** [wund3rcr4zy/by-the-book#4]
Reported By JSJosh from Discord:

"Out of curiosity, does the sync disc hijack an existing one? Because when I upgraded it at the clinic, I got the ability of the grow taller disc and fell through the floor"

**Comment by arjspe** [comment]
In the menu to install disks, there are no buttons on the left (just a salmon colored rectangle), the text shows #50/19, the description shows no text. After installing I can see a ";" where normally the description would be.

[Info   : ByTheBook] Attempting to install syncDisk group: private-eye_option1_0.
[Info   : ByTheBook] Found upgrades: 1
[Info   : ByTheBook] PrivateEyeUpgradeStatusChanged to: True
[Info   : ByTheBook] Found 12 enforcers to enabled dialog.

After installing the disk itself, my height hasn't changed. After installing the upgrade, I grew to what I think is max height (barely fit through a door whilst crouched) and after exiting the bed I fell through the floor.

[Info   : ByTheBook] Prefix: Attempting to install upgrade group: private-eye_option1_0.
[Info   : ByTheBook] Prefix: Found upgrades: 1
[Info   : ByTheBook] Attempting to install upgrade group: private-eye_option1_1.
[Info   : ByTheBook] Found upgrades: 2
[Info   : ByTheBook] PrivateEyeUpgradeStatusChanged to: True
[Info   : ByTheBook] Found 12 enforcers to enabled dialog.

**Comment by wund3rcr4zy** [comment]
Thanks for adding some context. Unfortunately, the latest game update broke another mod mine relies on. The "DDSLoader". This could explain why the text is not rendering for you. 

As that mod is not planned on being updated until the Mono branch is released, fixes for this mod are currently on hold.

**Comment by wund3rcr4zy** [comment]
This issue should be resolved with the version 0.2.0 release.
